import express from "express";
import multer from "multer";
import {createTeam,joinTeam,leftTeam,updateUser,getTeam} from "../controllers/team.controller.js";
import { updateProfileImage, updateCoverImage } from "../controllers/team.controller.js";
import { removeProfileImage, removeCoverImage } from "../controllers/team.controller.js";
import { protectRoute } from "../middleware/protectRoute.js";
const router=express.Router();
const storage = multer.memoryStorage();
const upload = multer({ storage });
router.put("/updateProfileImage", upload.single("img"), updateProfileImage);
router.put("/updateCoverImage", upload.single("img"), updateCoverImage);
router.put("/removeProfileImage", removeProfileImage);
router.put("/removeCoverImage", removeCoverImage);
router.post("/createTeam",createTeam);
router.post("/joinTeam",joinTeam);
router.post("/leftTeam",leftTeam);
router.post("/updateUser",updateUser);
router.post("/getTeam",getTeam);
export default router;